### Read And Understand World Data

In [84]:
import pandas as pd

In [106]:
full_world_df = pd.read_csv('https://raw.githubusercontent.com/owid/covid-19-data/master/public/data/owid-covid-data.csv')
cols_world_df = pd.read_csv('https://raw.githubusercontent.com/owid/covid-19-data/master/public/data/owid-covid-codebook.csv')

In [86]:
full_world_df.shape

(46902, 41)

In [87]:
cols_world_df

,column,description,source
0,iso_code,ISO 3166-1 alpha-3 – three-letter country codes,International Organization for Standardization
1,continent,Continent of the geographical location,Our World in Data
2,location,Geographical location,Our World in Data
3,date,Date of observation,Our World in Data
4,total_cases,Total confirmed cases of COVID-19,European Centre for Disease Prevention and Con...
5,new_cases,New confirmed cases of COVID-19,European Centre for Disease Prevention and Con...
6,new_cases_smoothed,New confirmed cases of COVID-19 (7-day smoothed),European Centre for Disease Prevention and Con...
7,total_deaths,Total deaths attributed to COVID-19,European Centre for Disease Prevention and Con...
8,new_deaths,New deaths attributed to COVID-19,European Centre for Disease Prevention and Con...
9,new_deaths_smoothed,New deaths attributed to COVID-19 (7-day smoot...,European Centre for Disease Prevention and Con...
10,total_cases_per_million,"Total confirmed cases of COVID-19 per 1,000,00...",European Centre for Disease Prevention and Con...
11,new_cases_per_million,"New confirmed cases of COVID-19 per 1,000,000 ...",European Centre for Disease Prevention and Con...
12,new_cases_smoothed_per_million,New confirmed cases of COVID-19 (7-day smoothe...,European Centre for Disease Prevention and Con...
13,total_deaths_per_million,"Total deaths attributed to COVID-19 per 1,000,...",European Centre for Disease Prevention and Con...
14,new_deaths_per_million,"New deaths attributed to COVID-19 per 1,000,00...",European Centre for Disease Prevention and Con...
15,new_deaths_smoothed_per_million,New deaths attributed to COVID-19 (7-day smoot...,European Centre for Disease Prevention and Con...
16,total_tests,Total tests for COVID-19,National government reports
17,new_tests,New tests for COVID-19,National government reports
18,new_tests_smoothed,New tests for COVID-19 (7-day smoothed). For c...,National government reports
19,total_tests_per_thousand,"Total tests for COVID-19 per 1,000 people",National government reports
20,new_tests_per_thousand,"New tests for COVID-19 per 1,000 people",National government reports
21,new_tests_smoothed_per_thousand,"New tests for COVID-19 (7-day smoothed) per 1,...",National government reports
22,tests_per_case,Tests conducted per new confirmed case of COVI...,National government reports
23,positive_rate,"The share of COVID-19 tests that are positive,...",National government reports
24,tests_units,Units used by the location to report its testi...,National government reports
25,stringency_index,Government Response Stringency Index: composit...,"Oxford COVID-19 Government Response Tracker, B..."
26,population,Population in 2020,"United Nations, Department of Economic and Soc..."
27,population_density,"Number of people divided by land area, measure...","World Bank – World Development Indicators, sou..."
28,median_age,"Median age of the population, UN projection fo...","UN Population Division, World Population Prosp..."
29,aged_65_older,Share of the population that is 65 years and o...,"World Bank – World Development Indicators, bas..."
30,aged_70_older,Share of the population that is 70 years and o...,"United Nations, Department of Economic and Soc..."
31,gdp_per_capita,Gross domestic product at purchasing power par...,"World Bank – World Development Indicators, sou..."
32,extreme_poverty,Share of the population living in extreme pove...,"World Bank – World Development Indicators, sou..."
33,cardiovasc_death_rate,Death rate from cardiovascular disease in 2017...,Global Burden of Disease Collaborative Network...
34,diabetes_prevalence,Diabetes prevalence (% of population aged 20 t...,"World Bank – World Development Indicators, sou..."
35,female_smokers,"Share of women who smoke, most recent year ava...","World Bank – World Development Indicators, sou..."
36,male_smokers,"Share of men who smoke, most recent year avail...","World Bank – World Development Indicators, sou..."
37,handwashing_facilities,Share of the population with basic handwashing...,United Nations Statistics Division
38,hospital_beds_per_thousand,"Hospital beds per 1,000 people, most recent ye...","OECD, Eurostat, World Bank, national governmen..."
39,life_expectancy,Life expectancy at birth in 2019,"James C. Riley, Clio Infra, United Nations Pop..."
40,human_development_index,Summary measure of average achievement in key ...,United Nations Development Programme (UNDP)

Line Graph Columns = [total_cases, new_cases, total_deaths, new_deaths, total_test, new_tests, tests_per_case, positive_rate ]\
    - Line Graph Options: location -- Dropdown, per capita or total -- Radio Buttons

In [88]:
full_world_df.head()

,iso_code,continent,location,date,total_cases,new_cases,new_cases_smoothed,total_deaths,new_deaths,new_deaths_smoothed,...,gdp_per_capita,extreme_poverty,cardiovasc_death_rate,diabetes_prevalence,female_smokers,male_smokers,handwashing_facilities,hospital_beds_per_thousand,life_expectancy,human_development_index
0,AFG,Asia,Afghanistan,2019-12-31,0.0,0.0,NaN,0.0,0.0,NaN,...,1803.987,NaN,597.029,9.59,NaN,NaN,37.746,0.5,64.83,0.498
1,AFG,Asia,Afghanistan,2020-01-01,0.0,0.0,NaN,0.0,0.0,NaN,...,1803.987,NaN,597.029,9.59,NaN,NaN,37.746,0.5,64.83,0.498
2,AFG,Asia,Afghanistan,2020-01-02,0.0,0.0,NaN,0.0,0.0,NaN,...,1803.987,NaN,597.029,9.59,NaN,NaN,37.746,0.5,64.83,0.498
3,AFG,Asia,Afghanistan,2020-01-03,0.0,0.0,NaN,0.0,0.0,NaN,...,1803.987,NaN,597.029,9.59,NaN,NaN,37.746,0.5,64.83,0.498
4,AFG,Asia,Afghanistan,2020-01-04,0.0,0.0,NaN,0.0,0.0,NaN,...,1803.987,NaN,597.029,9.59,NaN,NaN,37.746,0.5,64.83,0.498

### Read And Understand United States Data

In [44]:
full_usa_df = pd.read_csv('https://api.covidtracking.com/v1/states/daily.csv')

In [45]:
full_usa_df.head()

,date,state,positive,negative,pending,totalTestResults,hospitalizedCurrently,hospitalizedCumulative,inIcuCurrently,inIcuCumulative,...,posNeg,deathIncrease,hospitalizedIncrease,hash,commercialScore,negativeRegularScore,negativeScore,positiveScore,score,grade
0,20200929,AK,8674.0,442382.0,NaN,451056.0,49.0,NaN,NaN,NaN,...,451056,0,0,afd7a94cb0564b8c08d0c7d5a35034687ec529f9,0,0,0,0,0,NaN
1,20200929,AL,153554.0,983163.0,NaN,1119712.0,773.0,17182.0,NaN,1802.0,...,1136717,16,91,f5cbe33a7d909f209064f42c91980edc96c86a63,0,0,0,0,0,NaN
2,20200929,AR,82755.0,927902.0,NaN,1007905.0,491.0,5354.0,231.0,NaN,...,1010657,21,106,9674fdb795a3ec95f1a8018f9c8115611270bd2a,0,0,0,0,0,NaN
3,20200929,AS,0.0,1571.0,NaN,1571.0,NaN,NaN,NaN,NaN,...,1571,0,0,713455ea3b0b8f55ade2e9e1ed521e7e7e43ff81,0,0,0,0,0,NaN
4,20200929,AZ,218184.0,1239906.0,NaN,1453528.0,540.0,22047.0,119.0,NaN,...,1458090,9,28,aff6e79d8385633b46e9e237ccc3ec4b39f3138e,0,0,0,0,0,NaN

In [46]:
full_usa_df.shape

(11746, 54)

### Preprocessing United States Data

In [47]:
imp_features = ['date','state','death','deathIncrease','lastUpdateEt','negative','onVentilatorCurrently','positive','positiveIncrease','recovered','totalTestResults','totalTestResultsIncrease']

In [48]:
full_usa_df = full_usa_df[imp_features]
full_usa_df.rename(columns={'death':'Total Deaths','deathIncrease':'New Deaths','negative':'Total Negative Cases','onVentilatorCurrently':'Total Currently On Ventilator','positive':'Total Positive Cases','positiveIncrease':'New Positive Cases','recovered':'Total Recovered','totalTestResults':'Total Test Results','totalTestResultsIncrease':'New Test Results'}, inplace=True)

In [49]:
# Dict from this repo: https://gist.github.com/rogerallen/1583593
us_state_abbrev = {
    'Alabama': 'AL',
    'Alaska': 'AK',
    'Arizona': 'AZ',
    'Arkansas': 'AR',
    'California': 'CA',
    'Colorado': 'CO',
    'Connecticut': 'CT',
    'Delaware': 'DE',
    'District of Columbia': 'DC',
    'Florida': 'FL',
    'Georgia': 'GA',
    'Hawaii': 'HI',
    'Idaho': 'ID',
    'Illinois': 'IL',
    'Indiana': 'IN',
    'Iowa': 'IA',
    'Kansas': 'KS',
    'Kentucky': 'KY',
    'Louisiana': 'LA',
    'Maine': 'ME',
    'Maryland': 'MD',
    'Massachusetts': 'MA',
    'Michigan': 'MI',
    'Minnesota': 'MN',
    'Mississippi': 'MS',
    'Missouri': 'MO',
    'Montana': 'MT',
    'Nebraska': 'NE',
    'Nevada': 'NV',
    'New Hampshire': 'NH',
    'New Jersey': 'NJ',
    'New Mexico': 'NM',
    'New York': 'NY',
    'North Carolina': 'NC',
    'North Dakota': 'ND',
    'Ohio': 'OH',
    'Oklahoma': 'OK',
    'Oregon': 'OR',
    'Pennsylvania': 'PA',
    'Rhode Island': 'RI',
    'South Carolina': 'SC',
    'South Dakota': 'SD',
    'Tennessee': 'TN',
    'Texas': 'TX',
    'Utah': 'UT',
    'Vermont': 'VT',
    'Virginia': 'VA',
    'Washington': 'WA',
    'West Virginia': 'WV',
    'Wisconsin': 'WI',
    'Wyoming': 'WY'
}

full_usa_df = full_usa_df[full_usa_df['state'].isin(us_state_abbrev.values())]

#flip dictionary
us_state_abbrev_dict = {value : key for (key, value) in us_state_abbrev.items()}

In [50]:
def get_state_df(df, state):
    return df[df['state'] == state]

In [51]:
dropdownoptions = ['Total Positive Cases','New Positive Cases','Total Deaths','New Deaths','Total Currently On Ventilator','Total Negative Cases','Total Recovered','Total Test Results','New Test Results']

In [52]:
import datetime
import time

full_usa_df['date'] = pd.to_datetime(full_usa_df['date'], format='%Y%m%d')

def convert_to_unixtime(dt):
    return int(time.mktime(dt.timetuple()))

def convert_to_datetime(dt):
    return datetime.datetime.fromtimestamp(int(dt)).strftime('%Y-%m-%d %H:%M:%S')

In [53]:
full_usa_df.head()

,date,state,Total Deaths,New Deaths,lastUpdateEt,Total Negative Cases,Total Currently On Ventilator,Total Positive Cases,New Positive Cases,Total Recovered,Total Test Results,New Test Results
0,2020-09-29,AK,56.0,0,9/29/2020 03:59,442382.0,7.0,8674.0,125,4324.0,451056.0,6265
1,2020-09-29,AL,2517.0,16,9/29/2020 11:00,983163.0,NaN,153554.0,571,64583.0,1119712.0,3366
2,2020-09-29,AR,1350.0,21,9/29/2020 00:00,927902.0,98.0,82755.0,706,74440.0,1007905.0,10207
4,2020-09-29,AZ,5632.0,9,9/29/2020 00:00,1239906.0,64.0,218184.0,674,35125.0,1453528.0,4816
5,2020-09-29,CA,15640.0,32,9/29/2020 02:59,13806120.0,NaN,807425.0,2162,NaN,14613545.0,128693

In [54]:
usa_df = full_usa_df

In [55]:
usa_df.date.max()

Timestamp('2020-09-29 00:00:00')

In [56]:
usa_table_df = usa_df.loc[usa_df.date == usa_df.date.max()]

### Preprocessing World Data

In [107]:
countries_list = full_world_df['location'].unique()

In [108]:
def get_important_countries(countries_list):
    cl=[]
    for country in countries_list:
        if len(full_world_df.loc[full_world_df.location == country]) > 200:
            cl.append(country)
    return cl

imp_countries = get_important_countries(countries_list)
#print(imp_countries)

In [109]:
important_cols = ['total_cases','new_cases_smoothed','total_deaths','new_deaths_smoothed','total_tests','new_tests_smoothed','total_cases_per_million','new_cases_smoothed_per_million','total_deaths_per_million','new_deaths_smoothed_per_million','total_tests_per_thousand','new_tests_smoothed_per_thousand']

In [110]:
important_cols = ['total_cases','new_cases_smoothed','total_deaths','new_deaths_smoothed','total_tests','new_tests_smoothed','total_cases_per_million','new_cases_smoothed_per_million','total_deaths_per_million','new_deaths_smoothed_per_million','total_tests_per_thousand','new_tests_smoothed_per_thousand']
line_graph_cols = ['Total Cases','New Cases', 'Total Deaths', 'New Deaths', 'Total Tests', 'New Tests', 'Total Cases Per Million', 'New Cases Per Million', 'Total Deaths Per Million', 'New Deaths Per Million', 'Total Tests Per Thousand', 'New Tests Per Thousand']
total_line_graph_cols = ['Total Cases','New Cases', 'Total Deaths', 'New Deaths', 'Total Tests', 'New Tests']
per_capita_line_graph_cols = ['Total Cases Per Million', 'New Cases Per Million', 'Total Deaths Per Million', 'New Deaths Per Million', 'Total Tests Per Thousand', 'New Tests Per Thousand']
table_cols = ['Date', 'Country'] + line_graph_cols

In [117]:
temp_df = full_world_df.groupby('location').fillna(method='ffill')

,iso_code,continent,date,total_cases,new_cases,new_cases_smoothed,total_deaths,new_deaths,new_deaths_smoothed,total_cases_per_million,...,gdp_per_capita,extreme_poverty,cardiovasc_death_rate,diabetes_prevalence,female_smokers,male_smokers,handwashing_facilities,hospital_beds_per_thousand,life_expectancy,human_development_index
0,AFG,Asia,2019-12-31,0.0,0.0,NaN,0.0,0.0,NaN,0.0,...,1803.987,NaN,597.029,9.59,NaN,NaN,37.746,0.5,64.83,0.498
1,AFG,Asia,2020-01-01,0.0,0.0,NaN,0.0,0.0,NaN,0.0,...,1803.987,NaN,597.029,9.59,NaN,NaN,37.746,0.5,64.83,0.498
2,AFG,Asia,2020-01-02,0.0,0.0,NaN,0.0,0.0,NaN,0.0,...,1803.987,NaN,597.029,9.59,NaN,NaN,37.746,0.5,64.83,0.498
3,AFG,Asia,2020-01-03,0.0,0.0,NaN,0.0,0.0,NaN,0.0,...,1803.987,NaN,597.029,9.59,NaN,NaN,37.746,0.5,64.83,0.498
4,AFG,Asia,2020-01-04,0.0,0.0,NaN,0.0,0.0,NaN,0.0,...,1803.987,NaN,597.029,9.59,NaN,NaN,37.746,0.5,64.83,0.498
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
46897,NaN,NaN,2020-09-25,696.0,-9.0,-1.286,7.0,1.0,0.143,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
46898,NaN,NaN,2020-09-26,696.0,-9.0,-1.286,7.0,1.0,0.143,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
46899,NaN,NaN,2020-09-27,696.0,-9.0,-1.286,7.0,1.0,0.143,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
46900,NaN,NaN,2020-09-28,696.0,-9.0,-1.286,7.0,1.0,0.143,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
46901,NaN,NaN,2020-09-29,696.0,-9.0,-1.286,7.0,1.0,0.143,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [96]:
full_world_df.rename(columns={i:j for i,j in zip(important_cols,line_graph_cols)}, inplace=True)
full_world_df.rename(columns={'date':'Date', 'location':'Country'}, inplace=True)

In [73]:
def get_country_df(country):
    return full_world_df[full_world_df['Country'] == country]

In [74]:
world_df = full_world_df.loc[full_world_df.Country.isin(imp_countries)]
world_df = world_df[table_cols]

In [75]:
world_table_df = world_df.loc[world_df.Date == world_df.Date.max()]

In [104]:
world_table_df.head()

,Date,Country,Total Cases,New Cases,Total Deaths,New Deaths,Total Tests,New Tests,Total Cases Per Million,New Cases Per Million,Total Deaths Per Million,New Deaths Per Million,Total Tests Per Thousand,New Tests Per Thousand
273,2020-09-29,Afghanistan,39239.0,23.571,1456.0,1.714,NaN,NaN,1007.980,0.606,37.402,0.044,NaN,NaN
478,2020-09-29,Albania,13391.0,122.286,380.0,2.286,NaN,NaN,4653.207,42.493,132.045,0.794,NaN,NaN
752,2020-09-29,Algeria,51213.0,170.000,1719.0,5.714,NaN,NaN,1167.886,3.877,39.201,0.130,NaN,NaN
958,2020-09-29,Andorra,1966.0,40.714,53.0,0.000,NaN,NaN,25444.897,526.943,685.951,0.000,NaN,NaN
1763,2020-09-29,Argentina,723119.0,11855.000,16113.0,375.857,NaN,NaN,15999.703,262.303,356.516,8.316,NaN,NaN

### Dash Application

In [112]:
import dash
import dash_core_components as dcc
import dash_html_components as html
from dash.dependencies import Input, Output
import plotly.express as px

In [113]:
external_stylesheets = ['https://codepen.io/chriddyp/pen/bWLwgP.css']

covidapp = dash.Dash(__name__, external_stylesheets=external_stylesheets)

covidapp.layout = html.Div([
    html.H1('Covid Dashboard', style={'text-align':'center'}),
    
    dcc.Tabs([
        
        dcc.Tab(label='World', children=[
    
        html.Div([
            html.P('Select Country: '),
        
            dcc.Dropdown(
            id='country',
            options=[{'label': i, 'value': i} for i in imp_countries],
            value='United States'
            )
        
        ],style={'width':'40%', 'display':'inline-block'}),
        
        html.Div([
            html.P('Select Metric: '),
        
            dcc.RadioItems(
            id='total_percapita',
            options=[{'label': i, 'value': i} for i in ['Total', 'Per Capita']],
            value='Total',
            labelStyle={'display':'inline-block','text-align':'justify'}
            )
        ],style={'width':'40%','display': 'inline-block', 'float':'right'}),

        dcc.Graph(id='totalcases_line'),
        html.P('Source: European Centre for Disease Prevention and Control', style={'fontSize':10,'text-align':'center'}),
        dcc.Graph(id='newcases_line'),
        html.P('Source: European Centre for Disease Prevention and Control', style={'fontSize':10,'text-align':'center'}),
        dcc.Graph(id='totaldeaths_line'),
        html.P('Source: European Centre for Disease Prevention and Control', style={'fontSize':10,'text-align':'center'}),
        dcc.Graph(id='newdeaths_line'),
        html.P('Source: European Centre for Disease Prevention and Control', style={'fontSize':10,'text-align':'center'}),
        dcc.Graph(id='totaltests_line'),
        html.P('Source: National government reports', style={'fontSize':10,'text-align':'center'}),
        dcc.Graph(id='newtests_line'),
        html.P('Source: National government reports', style={'fontSize':10,'text-align':'center'})
    
        ]),
    
        dcc.Tab(label='United States', children=[
            
            html.Div([
                dcc.Dropdown(
                id='choropleth_dropdown',
                options=[{'label': i, 'value': i} for i in dropdownoptions],
                value='Total Positive Cases'
                )
            ]),
            
            dcc.Graph(id='choropleth'),
            
            html.Div([
                dcc.Slider(
                    id='choropleth_slider',
                    min=convert_to_unixtime(usa_df['date'].min()),
                    max=convert_to_unixtime(usa_df['date'].max()),
                    value=convert_to_unixtime(usa_df['date'].max()),
                    step=86400
                )
            ]),
            html.Div(id='selected_date'),
            
            html.Div([
                dcc.Dropdown(
                    id='state',
                    options=[{'label': i, 'value': i} for i in us_state_abbrev_dict.values()],
                    value='New Jersey'
                )
            ]),

            dcc.Graph(id='total_positive_line'),
            dcc.Graph(id='new_positive_line'),
            dcc.Graph(id='total_death_line'),
            dcc.Graph(id='new_death_line'),
            dcc.Graph(id='total_ventilator_line'),
            dcc.Graph(id='total_negative_line'),
            dcc.Graph(id='total_recovered_line'),
            dcc.Graph(id='total_test_line'),
            dcc.Graph(id='new_test_line')
            
        ])
        
    ])
])

@covidapp.callback(
    [Output('totalcases_line', 'figure'),
     Output('newcases_line', 'figure'),
     Output('totaldeaths_line', 'figure'),
     Output('newdeaths_line', 'figure'),
     Output('totaltests_line', 'figure'),
     Output('newtests_line', 'figure')],
    [Input('country','value'),
     Input('total_percapita', 'value')])

def update_world_graphs(country, total_percapita):
    country_df = get_country_df(country)
    world_line_graphs = []
    
    if total_percapita == 'Total':
    
        for option in total_line_graph_cols:
            world_line_graphs.append(px.line(country_df, x='Date', y=option, title=f'{country} {option}'))
    
        return world_line_graphs[0], world_line_graphs[1], world_line_graphs[2], world_line_graphs[3], world_line_graphs[4], world_line_graphs[5]
    
    else:
        
        for option in per_capita_line_graph_cols:
            world_line_graphs.append(px.line(country_df, x='Date', y=option, title=f'{country} {option}'))
            
        return world_line_graphs[0], world_line_graphs[1], world_line_graphs[2], world_line_graphs[3], world_line_graphs[4], world_line_graphs[5]
        
        
@covidapp.callback(
    [Output('choropleth', 'figure'),
     Output('selected_date', 'children'),
     Output('total_positive_line', 'figure'),
     Output('new_positive_line', 'figure'),
     Output('total_death_line', 'figure'),
     Output('new_death_line', 'figure'),
     Output('total_ventilator_line', 'figure'),
     Output('total_negative_line', 'figure'),
     Output('total_recovered_line', 'figure'),
     Output('total_test_line', 'figure'),
     Output('new_test_line', 'figure')],
    [Input('choropleth_dropdown', 'value'),
     Input('choropleth_slider', 'value'),
     Input('state', 'value')])

def update_USA_graphs(choropleth_dropdown, choropleth_slider, state):
    #Choropleth
    dt = pd.to_datetime(convert_to_datetime(choropleth_slider)).normalize()
    day_df = usa_df.loc[usa_df['date'] == dt]
    choropleth = px.choropleth(day_df, locations='state', locationmode='USA-states', color=choropleth_dropdown, projection='albers usa')

    #Line graphs
    state_df = get_state_df(usa_df, us_state_abbrev[state])
    usa_line_graphs = []
    for option in dropdownoptions:
        usa_line_graphs.append(px.line(state_df, x='date', y=option, title=f'{state} {option}'))
    
    date_selection_string = f'Selected Date: {dt.month_name()} {dt.day}, {dt.year}'
    
    return choropleth, date_selection_string, usa_line_graphs[0], usa_line_graphs[1], usa_line_graphs[2], usa_line_graphs[3], usa_line_graphs[4], usa_line_graphs[5], usa_line_graphs[6], usa_line_graphs[7], usa_line_graphs[8]
    
if __name__ == '__main__':
    covidapp.run_server(debug=True, use_reloader=False)

Dash is running on http://127.0.0.1:8050/

Dash is running on http://127.0.0.1:8050/

 * Serving Flask app "__main__" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: on